name: PYPI Build and Publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:       # See https://stackoverflow.com/questions/57699839/github-actions-how-to-target-all-branches-except-master for choices
      - '**'        # matches every branch

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

  workflow_run:
    workflows: ["Test Python Code"]
    types:
      - completed

env:
  # TODO: Change variable to your image's name.
  PACKAGE_NAME: "datatoolkit"

jobs:
  build:
    name: Build Python package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Build Package
        run: make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pypi_artifacts
          path: |
            build/
            dist/
            $PACKAGE_NAME.egg-info/

  publish:
    name: Publish to PYPI
    needs: [build]
    runs-on: ubuntu-latest
    if: always() # Need this to run sequentially

    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v2
        with:
          name: pypi_artifacts 

      # - name: Publish package
      #   if: startsWith(github.ref, 'refs/tags/')
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
      #     # repository_url: https://test.pypi.org/legacy/
      #     packages_dir: dist/
      #     verify_metadata: false
      #     verbose: true
      #     skip_existing: true

      - name: Publish package
        run: PYPI_API_TOKEN=$PYPI_API_TOKEN make publish