name: Pytest

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:       # See https://stackoverflow.com/questions/57699839/github-actions-how-to-target-all-branches-except-master for choices
      - '**'        # matches every branch

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  test_mock_dataset:
    name: Test mock_dataset.py
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}/datatoolkit
      # options: --user vscode
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: pytest tests/test_mock_dataset.py